Repository ISIS3510-202320-Team13/Android_Kotlin, pull requests merged in 2023-12, with the labels that each got.

#54 Micro-optimization and new Feature
  app/src/main/java/com/example/parkezkotlin/data/model/Reservation.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/ReservationViewModel.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/reservationAdapter.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/CurrentReservations.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/MapsFragment.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/ParkingDetail.kt
  app/src/main/res/drawable/baseline_calendar_month_24.xml
  app/src/main/res/layout/fragment_current_reservations.xml
  app/src/main/res/layout/item_reservation.xml
  app/src/main/res/navigation/parkeznavigation.xml
Labels: enhancement

#55 Fix for BQ - range implemented
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/ParkingDetail.kt
Labels: feature, fix

#58 Past reservations recyclerView implemented
  app/build.gradle.kts
  app/src/main/java/com/example/parkezkotlin/placeholder/PlaceholderContent.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/PastReservations.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/Settings.kt
  app/src/main/res/layout/fragment_past_reservations.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/navigation/parkeznavigation.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#59 Developer new features fixing bugs
  app/build.gradle.kts
  app/src/main/java/com/example/parkezkotlin/data/model/Reservation.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/ReservationViewModel.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/parkingViewModel.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/reservationAdapter.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/Booking_info.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/CurrentReservations.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/LoginFragment.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/MainActivity.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/MapsFragment.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/MetodoDePago.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/ParkingDetail.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/PastReservations.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/Recibos.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/Settings.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/custom_time_picker.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/search.kt
  app/src/main/res/drawable/round_manage_accounts_24.xml
  app/src/main/res/layout/fragment_current_reservations.xml
  app/src/main/res/layout/fragment_maps.xml
  app/src/main/res/layout/fragment_metodo_de_pago.xml
  app/src/main/res/layout/fragment_parking_detail.xml
  app/src/main/res/layout/fragment_recibos.xml
  app/src/main/res/layout/fragment_search2.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/layout/item_reservation.xml
  app/src/main/res/navigation/parkeznavigation.xml
Labels: bug, help wanted, feature

#61 Cache for reservations and showing parking lot names
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/ReservationViewModel.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/reservationAdapter.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/CurrentReservations.kt
  app/src/main/res/drawable/baseline_history_24.xml
Labels: enhancement, feature

#64 Fixes to UI and BQ implemented
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/ReservationViewModel.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/MetodoDePago.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/Settings.kt
  app/src/main/res/layout/fragment_current_reservations.xml
  app/src/main/res/layout/fragment_maps.xml
  app/src/main/res/layout/fragment_settings.xml
Labels: feature, fix

#66 fixing errors and bugs
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/ParkingDetail.kt
  app/src/main/java/com/example/parkezkotlin/ui/viewModel/view/Recibos.kt
  app/src/main/res/layout/fragment_current_reservations.xml
  app/src/main/res/layout/fragment_maps.xml
  app/src/main/res/layout/fragment_recibos.xml
  app/src/main/res/layout/fragment_settings.xml
Labels: bug
